# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171031_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttoreview',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 22, 36, 0, 76070)),
        ),
    ]
