# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171101_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 16, 6, 17, 116241)),
        ),
    ]
